# Generated by Django 3.2.22 on 2023-11-19 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_report', '0001_initial'),
        ('accounts', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBillHistoryHead',
            fields=[
                ('head_id', models.AutoField(primary_key=True, serialize=False)),
                ('cash', models.IntegerField(default=0, null=True)),
                ('online', models.IntegerField(default=0, null=True)),
                ('remaining', models.IntegerField(default=0, null=True)),
                ('grand_total', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctoruser')),
                ('header_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_report.headerpatient')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitaluser')),
                ('main_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.mainstore')),
                ('mini_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ministore')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patientuser')),
            ],
            options={
                'db_table': 'patient_bill_history_head',
            },
        ),
        migrations.CreateModel(
            name='PatientBillHistoryDetails',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.patientbillhistoryhead')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.medicine')),
            ],
            options={
                'db_table': 'patient_bill_history_details',
            },
        ),
        migrations.CreateModel(
            name='PatientBillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=1000)),
                ('qty', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=1000)),
                ('patient', models.IntegerField()),
                ('hospital', models.IntegerField()),
                ('doctor', models.IntegerField()),
                ('grand_total', models.IntegerField()),
                ('cash', models.IntegerField(default=0)),
                ('online', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('header_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_report.headerpatient')),
            ],
            options={
                'db_table': 'Patient_bill_history',
            },
        ),
    ]
