# Generated by Django 3.2.22 on 2023-11-09 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=1000)),
                ('qty', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=1000)),
                ('patient', models.IntegerField()),
                ('hospital', models.IntegerField()),
                ('doctor', models.IntegerField()),
                ('grand_total', models.IntegerField()),
                ('cash', models.IntegerField(default=0)),
                ('online', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('header_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_report.headerpatient')),
            ],
            options={
                'db_table': 'Patient_bill_history',
            },
        ),
    ]
