# Generated by Django 3.2.22 on 2023-11-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_report', '0007_auto_20231108_1933'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbillhistory',
            name='header_patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient_report.headerpatient'),
            preserve_default=False,
        ),
    ]
