# Generated by Django 3.2.22 on 2023-11-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_patientbillhistorydetails_patientbillhistoryhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbillhistorydetails',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientbillhistorydetails',
            name='qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientbillhistorydetails',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientbillhistoryhead',
            name='cash',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientbillhistoryhead',
            name='online',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientbillhistoryhead',
            name='remaining',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
