# Generated by Django 3.2.22 on 2023-11-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20231109_1557'),
        ('billing', '0003_auto_20231115_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbillhistoryhead',
            name='mini_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.ministore'),
            preserve_default=False,
        ),
    ]
