# Generated by Django 3.2.22 on 2023-11-16 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20231114_1250'),
        ('billing', '0004_patientbillhistoryhead_mini_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbillhistoryhead',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctoruser'),
        ),
        migrations.AlterField(
            model_name='patientbillhistoryhead',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patientuser'),
        ),
    ]
