# Generated by Django 3.2.22 on 2023-11-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20231109_1557'),
        ('billing', '0005_auto_20231116_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbillhistoryhead',
            name='main_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.mainstore'),
            preserve_default=False,
        ),
    ]
