# Generated by Django 3.2.22 on 2023-11-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20231109_1557'),
        ('billing', '0006_patientbillhistoryhead_main_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbillhistoryhead',
            name='main_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.mainstore'),
        ),
        migrations.AlterField(
            model_name='patientbillhistoryhead',
            name='mini_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ministore'),
        ),
    ]
