# Generated by Django 3.2.22 on 2023-11-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_report', '0001_initial'),
        ('billing', '0007_auto_20231118_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbillhistoryhead',
            name='header_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_report.headerpatient'),
        ),
    ]
