# Generated by Django 3.2.22 on 2023-11-03 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMedicalStoreMedicineTransactionHistory',
            fields=[
                ('medicine_trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_qty', models.IntegerField()),
                ('trans_created', models.DateField(auto_now_add=True)),
                ('trans_update', models.DateField(null=True)),
                ('mapping_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.mappingmedicine')),
            ],
        ),
    ]
