# Generated by Django 3.2.22 on 2023-10-27 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainStore',
            fields=[
                ('main_store_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_hospital_user', to='accounts.hospitaluser')),
                ('main_store_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_store_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_store',
            },
        ),
        migrations.CreateModel(
            name='MappingMedicine',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('expiration', models.DateField()),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('main_store_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_main_store_user', to='store.mainstore')),
            ],
            options={
                'db_table': 'mapping_medicine',
            },
        ),
        migrations.CreateModel(
            name='MappingMiniStorMedicine',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('mini_qty', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_mini_store_medicine', to='store.mappingmedicine')),
                ('mini_store_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_mini_store_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mapping_mini_store_medicine',
            },
        ),
        migrations.CreateModel(
            name='MedicineTransactionHistory',
            fields=[
                ('medicine_trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_main_qty', models.IntegerField(default=0)),
                ('trans_mini_qty', models.IntegerField(default=0)),
                ('trans_date', models.DateTimeField(auto_now_add=True)),
                ('main_store_medicine_trans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_store_medicine_trans', to='store.mappingmedicine')),
                ('mini_store_medicine_trans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_store_medicine_trans', to='store.mappingministormedicine')),
            ],
        ),
        migrations.CreateModel(
            name='MiniStore',
            fields=[
                ('main_store_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_hospital_user', to='accounts.hospitaluser')),
                ('mini_store_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_store_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mini_store',
            },
        ),
        migrations.RemoveField(
            model_name='minimedicalstore',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='minimedicalstore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ministoremedicine',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='ministoremedicine',
            name='mini_store',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='main_medicine_id',
            new_name='medicine_id',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='main_store',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='price',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MainMedicalStore',
        ),
        migrations.DeleteModel(
            name='MiniMedicalStore',
        ),
        migrations.DeleteModel(
            name='MiniStoreMedicine',
        ),
        migrations.AddField(
            model_name='mappingmedicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_medicine', to='store.medicine'),
        ),
    ]
