# Generated by Django 3.2.23 on 2023-11-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainstoremedicine',
            name='from_mini_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MainStoreMedicine_from_mini_store', to='accounts.stores'),
        ),
    ]
