# Generated by Django 3.2.22 on 2023-11-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minimedicalstoremedicinetransactionhistory',
            name='mini_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mini_trans_mini_store_user', to='store.ministore'),
        ),
        migrations.AlterField(
            model_name='minimedicalstoremedicinetransactionhistory',
            name='main_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mini_trans_main_store_user', to='store.mainstore'),
        ),
    ]
