# Generated by Django 3.2.22 on 2023-11-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_mainmedicalstoremedicinetransactionhistory_main_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmedicalstoremedicinetransactionhistory',
            old_name='mapping_medicine',
            new_name='medicine',
        ),
        migrations.CreateModel(
            name='MiniMedicalStoreMedicineTransactionHistory',
            fields=[
                ('medicine_trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_qty', models.IntegerField()),
                ('trans_created', models.DateField(auto_now_add=True)),
                ('trans_update', models.DateField(null=True)),
                ('main_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_trans_main_store_user', to='store.mainstore')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.medicine')),
            ],
            options={
                'db_table': 'mini_store_medicine_transaction_history',
            },
        ),
    ]
