# Generated by Django 3.2.22 on 2023-11-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0002_auto_20231119_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferMedicine',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(null=True)),
                ('from_main_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_main_store', to='store.mainstore')),
                ('from_mini_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_mini_store', to='store.ministore')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_hospital', to='accounts.hospitaluser')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_medicine', to='store.medicine')),
                ('to_main_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_main_store', to='store.mainstore')),
                ('to_mini_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_mini_store', to='store.ministore')),
            ],
            options={
                'db_table': 'transfer_medicine',
            },
        ),
    ]
