# Generated by Django 3.2.22 on 2023-11-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_mainmedicalstoremedicinetransactionhistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainmedicalstoremedicinetransactionhistory',
            table='main_store_medicine_transaction_history',
        ),
    ]
