# Generated by Django 3.2.22 on 2023-11-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_mainmedicalstoremedicinetransactionhistory_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingministormedicine',
            name='mini_store_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_mini_store_user', to='store.ministore'),
        ),
    ]
