# Generated by Django 3.2.22 on 2023-11-22 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_transfermedicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfermedicine',
            name='from_mini_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_mini_store', to='store.ministore'),
        ),
        migrations.AlterField(
            model_name='transfermedicine',
            name='to_mini_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_mini_store', to='store.ministore'),
        ),
    ]
