# Generated by Django 3.2.22 on 2023-11-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_mappingministormedicine_mini_store_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineTransactionHistory',
        ),
    ]
