# Generated by Django 3.2.22 on 2023-11-08 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_medicinetransactionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='hospital',
        ),
        migrations.AddField(
            model_name='medicine',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='main_store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mapping_main_store_user', to='store.mainstore'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='qty',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainmedicalstoremedicinetransactionhistory',
            name='mapping_medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.medicine'),
        ),
        migrations.AlterField(
            model_name='mappingministormedicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_mini_store_medicine', to='store.medicine'),
        ),
        migrations.AlterModelTable(
            name='medicine',
            table='main_store_medicine',
        ),
        migrations.DeleteModel(
            name='MappingMedicine',
        ),
    ]
