# Generated by Django 3.2.22 on 2023-11-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='appoint_status',
            field=models.CharField(default='unchecked', max_length=10),
        ),
    ]
