# Generated by Django 3.2.22 on 2023-10-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappointment',
            name='id',
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='patient_appoint_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
