# Generated by Django 3.2.23 on 2023-11-23 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('dashboard', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='appoint_ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.hospitalappointmentvisit'),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctoruser'),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitaluser'),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patientuser'),
        ),
    ]
