# Generated by Django 3.2.22 on 2023-11-13 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_hospitalappointmentvisit_hospital'),
        ('appointment', '0002_patientappointment_appoint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='appoint_ward',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.hospitalappointmentvisit'),
            preserve_default=False,
        ),
    ]
