# Generated by Django 3.2.22 on 2023-11-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_patientappointment_appoint_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
