# Generated by Django 3.2.22 on 2023-11-13 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_password'),
        ('dashboard', '0002_alter_hospitalappointmentvisit_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalappointmentvisit',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitaluser'),
            preserve_default=False,
        ),
    ]
