# Generated by Django 3.2.22 on 2023-11-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientuser',
            name='other_ref',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.otherreference'),
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='social_ref',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.socialmediareference'),
        ),
    ]
