# Generated by Django 3.2.22 on 2023-11-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupfield',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lookup_images'),
        ),
        migrations.AlterField(
            model_name='lookupfield',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='lookup_pdfs'),
        ),
        migrations.AlterField(
            model_name='lookupfield',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lookup_videos'),
        ),
    ]
