# Generated by Django 3.2.22 on 2023-10-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_auto_20231027_2021'),
        ('appointment', '0002_auto_20231028_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPatient',
            fields=[
                ('head_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.patientappointment')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsPatient',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_report.headerpatient')),
                ('medicine_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.medicine')),
            ],
        ),
    ]
