# Generated by Django 3.2.22 on 2023-11-13 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0003_auto_20231109_1557'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPatient',
            fields=[
                ('head_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease', models.TextField(blank=True, null=True)),
                ('doctor_status', models.CharField(default='unchecked', max_length=10)),
                ('bill_status', models.CharField(default='unbilled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.patientappointment')),
            ],
            options={
                'db_table': 'header_patient',
            },
        ),
        migrations.CreateModel(
            name='DetailsPatient',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('dosage', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_report.headerpatient')),
                ('medicine_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.medicine')),
            ],
            options={
                'db_table': 'details_patient',
            },
        ),
    ]
