# Generated by Django 3.2.22 on 2023-11-03 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPatient',
            fields=[
                ('head_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.patientappointment')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsPatient',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('dosage', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('created_time', models.TimeField(blank=True, null=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_report.headerpatient')),
                ('medicine_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.medicine')),
            ],
        ),
    ]
