# Generated by Django 3.2.22 on 2023-10-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailspatient',
            name='dosage',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detailspatient',
            name='frequency',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
