# Generated by Django 3.2.22 on 2023-11-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerpatient',
            name='disease',
            field=models.TextField(blank=True, null=True),
        ),
    ]
