# Generated by Django 3.2.22 on 2023-11-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headerpatient',
            old_name='status',
            new_name='bill_status',
        ),
        migrations.AddField(
            model_name='headerpatient',
            name='doctor_status',
            field=models.CharField(default='unchecked', max_length=10),
        ),
    ]
