# Generated by Django 3.2.22 on 2023-10-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_report', '0002_auto_20231028_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailspatient',
            name='created_at',
        ),
        migrations.AddField(
            model_name='detailspatient',
            name='created_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='detailspatient',
            name='created_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
