# Generated by Django 3.2.22 on 2023-11-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_report', '0002_headerpatient_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailspatient',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
