# Generated by Django 3.2.22 on 2023-10-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_report', '0003_auto_20231028_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailspatient',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailspatient',
            name='created_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
