# Generated by Django 3.2.22 on 2023-11-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_report', '0005_auto_20231105_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerpatient',
            name='status',
            field=models.CharField(default='unbilled', max_length=10),
        ),
    ]
