# Generated by Django 3.2.22 on 2023-11-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_report', '0006_headerpatient_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detailspatient',
            table='details_patient',
        ),
        migrations.AlterModelTable(
            name='headerpatient',
            table='header_patient',
        ),
    ]
